### ISSUE TITLE
-1 option error

### ISSUE THREAD

**Issue by haydenji0731** [JEFworks-Lab/off-target-probe-tracker#7]
Jean reported an error running the `-1` mode on Mac. Test and check.

**Comment by calebhallinan** [comment]
(opt) jeanfan@Profs-MBP ~/Desktop/off-target-probe-tracker % opt -o HuBMAP_test track -q HuBMAP_test/fwd_oriented.fa -a HuBMAP_test/gencode.v47.basic.annotation.fmted.gff -t HuBMAP_test/gencode.v47.basic.annotation.fmted.fa -1
2025-04-02 10:10:46.626127 PROGRESS ### TRACK ###
2025-04-02 10:10:46.626506 PROGRESS aligning query probes to target transcripts
2025-04-02 10:10:46.626523 PROGRESS aligner: mummer
mummer -maxmatch -l 20 -t 1 HuBMAP_test/gencode.v47.basic.annotation.fmted.fa HuBMAP_test/fwd_oriented.fa > HuBMAP_test/track.mums
2025-04-02 10:11:20.180553 PROGRESS loading target transcriptome infos
2025-04-02 10:11:23.653482 PROGRESS detecting potential off-target probe activities
Traceback (most recent call last):
  File "/Users/jeanfan/mambaforge/envs/opt/bin/opt", line 8, in <module>
    sys.exit(main())
  File "/Users/jeanfan/mambaforge/envs/opt/lib/python3.9/site-packages/opt/run_opt.py", line 110, in main
    track.main(args)
  File "/Users/jeanfan/mambaforge/envs/opt/lib/python3.9/site-packages/opt/track.py", line 379, in main
    ainfos = track_target_nm(afn, qfa, tfa, args.max_mismatch, tinfos)
AttributeError: 'Namespace' object has no attribute 'max_mismatch'

**Comment by haydenji0731** [comment]
fixed.

**Comment by MathiniVaikunthan** [comment]
Hello! I am still getting this error "AttributeError: 'Namespace' object has no attribute 'max_mismatch'" but I suspect I am just not able to get the latest updates that have been pushed, thank you for letting me know how to do so!
